# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('allowed', models.BooleanField()),
                ('reported', models.BooleanField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('udi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('preview', models.CharField(max_length=300)),
                ('tags', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shedule', models.DateTimeField(auto_now_add=True)),
                ('allwoed', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('udi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.Post')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lvl', models.PositiveSmallIntegerField()),
                ('avatar', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('udi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citrom_api.User'),
        ),
    ]
